services:
  api:
    build:
      target: production
    environment:
      NODE_ENV: production
      START_COMMAND: node dist/main
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped

  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  rabbitmq:
    restart: unless-stopped
