// @ts-check
import eslint from '@eslint/js';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';
import sonarjs from 'eslint-plugin-sonarjs';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // src/generated is the Prisma client: gitignored, regenerated by `prisma
    // generate`, ~19k lines. Every file already carries an `/* eslint-disable */`
    // header, but that only takes effect after the file has been fully parsed
    // with type information -- ignoring it outright skips that work entirely.
    ignores: ['eslint.config.mjs', 'src/generated/**'],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  // SonarJS: the same rule family SonarQube Cloud runs against this repo in CI,
  // available here at lint/pre-commit time instead of only after a push. Its
  // `recommended` config sets every enabled rule to `error`, so a finding fails
  // `npm run lint` rather than being lost among warnings. See
  // docs/code-quality.md for how to handle one.
  sonarjs.configs.recommended,
  eslintPluginPrettierRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
      sourceType: 'commonjs',
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-floating-promises': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      'prettier/prettier': ['error', { endOfLine: 'auto' }],

      // Cannot distinguish `T | null` from `T | undefined`, so it reports a
      // guaranteed-false comparison for every `nullableField === optionalArg`
      // even though the non-nullish arms overlap perfectly. Both occurrences in
      // this repo were that false positive. The real case this rule exists for
      // -- comparing genuinely non-overlapping types -- is already a hard
      // compile error (TS2367), so nothing is lost by turning it off.
      'sonarjs/different-types-comparison': 'off',
    },
  },
  {
    // Test-only rule scoping. Each rule below fires exclusively on test code in
    // this repo, and in every case the finding is a false positive or conflicts
    // with a convention CLAUDE.md documents -- so they are scoped off here
    // rather than worked around file by file.
    files: ['**/*.spec.ts', 'test/**/*.ts'],
    rules: {
      // supertest's own `.expect(200)` is the assertion; the rule only
      // recognises `expect()` from the test framework and flags every
      // request-chain test as assertion-less (73 findings, all e2e specs).
      'sonarjs/assertions-in-tests': 'off',
      // `Object.keys(x).sort()` compared against a sorted literal is an
      // order-insensitive set comparison over ASCII keys, not user-facing
      // alphabetical ordering.
      'sonarjs/no-alphabetical-sort': 'off',
      // Passing `undefined` explicitly is the behaviour under test (e.g.
      // "throws when the RunContext is missing entirely").
      'sonarjs/no-undefined-argument': 'off',
      // `void tasks` discards a binding destructured out solely to build an
      // invalid-args fixture.
      'sonarjs/void-use': 'off',
      // CLAUDE.md's testing conventions call for one behaviour statement per
      // `it()`; collapsing them into a parameterized table loses that.
      'sonarjs/parameterized-tests': 'off',
      // A `/tmp/...` string constant in a spec whose `fs` module is jest-mocked
      // is never written to.
      'sonarjs/publicly-writable-directories': 'off',
      // `execSync('npx prisma migrate deploy')` in the e2e global setup is
      // developer tooling, not production code resolving an attacker-controlled
      // PATH.
      'sonarjs/no-os-command-from-path': 'off',
      // The database-name guard spells its character class out in full on
      // purpose -- it is interpolated into a CREATE DATABASE statement, and
      // explicit beats concise for a SQL-injection guard.
      'sonarjs/concise-regex': 'off',
    },
  },
);
