// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import { expand } from 'dotenv-expand';
import { defineConfig } from 'prisma/config';

// Plain dotenv doesn't resolve ${VAR} references (e.g. DATABASE_URL built from
// POSTGRES_* in .env), so expand the parsed result before reading process.env below.
expand(dotenv.config());

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    // The CLI runs DDL (migrate/reset/seed/studio), so it needs a direct
    // connection: in deployed environments DATABASE_URL points at Neon's
    // transaction-mode pooler, which can't run migrations reliably. Falls back
    // to DATABASE_URL for local/Compose/e2e, where there's only one endpoint.
    url: process.env['DIRECT_DATABASE_URL'] ?? process.env['DATABASE_URL'],
  },
});
