# See imagepullpolicy-patch.yaml for why this is needed for kind.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekly-routine-cleanup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: weekly-routine-cleanup
              imagePullPolicy: Never
