import { randomUUID } from 'node:crypto';
import {
  AiProvider,
  ConfirmedRoutineCreation,
  CreateRoutineExecutor,
  GeneratedPracticePlan,
} from '../../src/ai-practice-planner/openai/ai-provider';
import { PracticePlan } from '../../src/ai-practice-planner/dto/practice-plan.schema';

/**
 * In-memory stand-in for OpenAiResponsesService, following the same
 * infra-boundary-swap pattern as FakeGcpStorageService/FakeRoutineEventsClient
 * (see build-test-app.ts). e2e specs never make real OpenAI calls.
 *
 * Configure the plan a test expects via `nextPlan`; `generatePracticePlan`
 * ignores the prompt text and just returns it, paired with a fresh fake
 * response id that `confirmAndCreateRoutine` accepts.
 */
export class FakeAiProvider implements AiProvider {
  nextPlan: PracticePlan = {
    title: '30-Minute Blues Practice',
    summary: 'Practice bending accuracy and blues improvisation.',
    totalDurationMinutes: 30,
    tasks: [
      {
        title: 'Warm-up',
        description: 'Finger warm-up exercises.',
        durationMinutes: 5,
      },
      {
        title: 'Bending practice',
        description: 'Target pitch bends.',
        durationMinutes: 10,
      },
      {
        title: 'Blues improvisation',
        description: 'Improvise over a 12-bar blues backing track.',
        durationMinutes: 15,
      },
    ],
    requiresConfirmation: true,
  };

  generatePracticePlan(): Promise<GeneratedPracticePlan> {
    return Promise.resolve({
      plan: this.nextPlan,
      previousResponseId: `resp_fake_${randomUUID()}`,
    });
  }

  async confirmAndCreateRoutine(
    previousResponseId: string,
    executeCreateRoutine: CreateRoutineExecutor,
  ): Promise<ConfirmedRoutineCreation> {
    const toolResult = await executeCreateRoutine({
      title: this.nextPlan.title,
      notes: 'Generated by AI Practice Planner',
      tasks: this.nextPlan.tasks,
    });

    return {
      finalMessage: `Created routine "${toolResult.title}" with ${toolResult.taskCount} tasks.`,
      toolResult,
    };
  }
}
